=== jtschichold/mm-cloud-services-miners/docs/schemas/AWSIPRangesMiner.schema.json
{
    "$id": "https://githb.com/jtschichold/mm-cloud-services-miners/AWSIPRangesMiner.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "minItems": 1,
    "items": {
        "type": "object",
        "properties": {
            "endpoint": {
                "type": "string"
            },
            "service": {
                "type": "string"
            },
            "region": {
                "type": "string"
            },
            "network_border_group": {
                "type": "string"
            }
        },
        "required": ["endpoint", "service", "region", "network_border_group"]
    }
}

=== jtschichold/mm-cloud-services-miners/__tests__/data/AWSIPRangesMiner-result.json
[
    {
        "endpoint": "3.5.140.0/22",
        "region": "ap-northeast-2",
        "service": "AMAZON",
        "network_border_group": "ap-northeast-2"
    },
    {
        "endpoint": "2a05:d07a:a000::/40",
        "region": "eu-south-1",
        "service": "AMAZON",
        "network_border_group": "eu-south-1"
    }
]
