=== jtschichold/mm-cloud-services-miners/docs/schemas/AzureWithServiceTagsMiner.schema.json
{
    "$id": "https://githb.com/jtschichold/mm-cloud-services-miners/AzureWithServiceTagsMiner.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "minItems": 1,
    "items": {
        "type": "object",
        "description": "Check https://www.microsoft.com/en-us/download/details.aspx?id=56519 for full documentation of the fields",
        "properties": {
            "endpoint": {
                "type": "string",
                "description": "Azure Service endpoint"
            },
            "cloud": {
                "type": "string",
                "description": "Azure Cloud (Public, ...) of this endpoint"
            },
            "id": {
                "type": "string",
                "description": "Azure Service Id in the original Azure Service JSON feed"
            },
            "name": {
                "type": "string",
                "description": "Azure Service Name in the original Azure Service JSON feed"
            },
            "region": {
                "type": "string",
                "description": "Azure Cloud region"
            },
            "regionId": {
                "type": "integer",
                "description": "Azure Cloud region Id"
            },
            "platform": {
                "type": "string",
                "description": "Azure Service platform"
            },
            "systemService": {
                "type": "string",
                "description": "Azure Service Name"
            },
            "networkFeatures": {
                "type": ["array", "null"],
                "items": {
                    "type": "string"
                }
            }
        },
        "required": [
            "endpoint",
            "id",
            "region",
            "regionId",
            "cloud",
            "systemService",
            "platform",
            "name"
        ]
    }
}

=== jtschichold/mm-cloud-services-miners/__tests__/data/AzureWithServiceTagsMiner-result.json
[
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.66.60.119/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.66.143.220/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.66.202.14/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.66.248.225/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.66.249.211/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.67.10.124/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.69.109.132/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.71.199.112/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.77.53.216/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.77.172.102/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.77.183.209/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.78.109.156/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.84.49.247/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.84.51.172/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.84.52.58/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.86.221.220/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.106.38.142/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.106.38.148/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.106.54.3/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.106.54.19/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.106.57.181/32"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "13.106.57.196/31"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "20.38.149.132/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "20.42.64.36/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "20.43.121.124/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "20.44.17.220/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
        "region": "",
        "regionId": 0,
        "platform": "Azure",
        "systemService": "ActionGroup",
        "networkFeatures": [
            "API",
            "NSG",
            "UDR",
            "FW"
        ],
        "endpoint": "20.45.123.236/30"
    },
    {
        "cloud": "Public",
        "id": "ActionGroup",
        "name": "ActionGroup",
