=== jtschichold/mm-cloud-services-miners/docs/schemas/O365Miner.schema.json
{
    "$id": "https://githb.com/jtschichold/mm-cloud-services-miners/O365Miner.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "minItems": 1,
    "items": {
        "type": "object",
        "description": "Check https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide for full documentation of the fields",
        "properties": {
            "endpoint": {
                "type": "string",
                "description": "O365 endpoint"
            },
            "endpointType": {
                "type": "string",
                "enum": [
                    "IP",
                    "URL"
                ],
                "description": "Type of endpoint "
            },
            "id": {
                "type": "integer",
                "description": "Service ID in the original O365 endpoints JSON feed"
            },
            "serviceArea": {
                "type": "string"
            },
            "serviceAreaDisplayName": {
                "type": "string"
            },
            "tcpPorts": {
                "type": ["string", "null"]
            },
            "udpPorts": {
                "type": ["string", "null"]
            },
            "expressRoute": {
                "type": "boolean"
            },
            "category": {
                "type": "string"
            },
            "required": {
                "type": "boolean"
            },
            "instance": {
                "type": "string"
            }
        },
        "required": [
            "endpoint",
            "endpointType",
            "id",
            "instance",
            "required",
            "serviceArea",
            "serviceAreaDisplayName",
            "category",
            "expressRoute"
        ]
    }
}

=== jtschichold/mm-cloud-services-miners/docs/O365Miner.json
[{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"13.107.6.152/31","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"13.107.18.10/31","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"13.107.128.0/22","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"23.103.160.0/20","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"40.96.0.0/13","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"40.104.0.0/15","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"52.96.0.0/14","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"131.253.33.215/32","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"132.245.0.0/16","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"150.171.32.0/22","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"204.79.197.215/32","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1006::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1016::/36","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1026::/36","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1036::/36","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1046::/36","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1056::/36","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1096::/38","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1096:400::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1096:600::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1096:a00::/39","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:1096:c00::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:10a6:200::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:10a6:400::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:10a6:600::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:10a6:800::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2603:10d6:200::/40","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:4::152/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:4::153/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:c::10/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:c::11/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:d::10/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:d::11/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:8f0::/46","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:900::/46","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:a92::152/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2620:1ec:a92::153/128","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"2a01:111:f400::/48","endpointType":"IP"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"outlook.office.com","endpointType":"URL"},{"id":1,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"80,443","expressRoute":true,"category":"Optimize","required":true,"instance":"Worldwide","endpoint":"outlook.office365.com","endpointType":"URL"},{"id":2,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"587","expressRoute":true,"category":"Allow","required":true,"instance":"Worldwide","endpoint":"13.107.6.152/31","endpointType":"IP"},{"id":2,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"587","expressRoute":true,"category":"Allow","required":true,"instance":"Worldwide","endpoint":"13.107.18.10/31","endpointType":"IP"},{"id":2,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"587","expressRoute":true,"category":"Allow","required":true,"instance":"Worldwide","endpoint":"13.107.128.0/22","endpointType":"IP"},{"id":2,"serviceArea":"Exchange","serviceAreaDisplayName":"Exchange Online","tcpPorts":"587","expressRoute":true,"category":"Allow","required":true,"instance":"Worldwide","endpoint":"23.103.1
